# Generated by Django 4.2.1 on 2025-05-15 21:16

import beeco_app.models.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beeco_app', '0003_remove_chatmessage_chat_remove_chatmessage_sender_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', beeco_app.models.user.CustomUserManager()),
            ],
        ),
    ]
