# Generated by Django 5.2.1 on 2025-05-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beeco_app', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
    ]
